### ISSUE TITLE
empty electron window

### ISSUE THREAD

**Issue by michaeljosephrosenthal** [IonicaBizau/magnesium#5]
after `npm i -g magnesium; magnesium`:
<img width="803" alt="screen shot 2016-01-12 at 15 56 33" src="https://cloud.githubusercontent.com/assets/8343799/12280737/20699f96-b945-11e5-8b6d-ec7c7ac50a60.png">

**Comment by IonicaBizau** [comment]
Whoups! :mask:  It happened because we should rebuild the modules after install. Addressed in https://github.com/IonicaBizau/magnesium/commit/845c4d96fc0a8d3065ff3a399183a01526f48588.

Run `npm i -g magnesium@latest` and then `magnesium` should work fine. :smile:
