### ISSUE TITLE
Saving session state between restarts

### ISSUE THREAD

**Issue by Goddard** [IonicaBizau/magnesium#8]
It would be really awesome if you could save tabs and sessions between reboots

**Comment by IonicaBizau** [comment]
@Goddard That's already possible by using `tmux`. Install tmux (`sudo apt-get install tmux` or `brew install tmux`). Then [install the Tmux Plugin manager](https://github.com/tmux-plugins/tpm#installation) and then install [`tmux-resurect`](https://github.com/tmux-plugins/tmux-resurrect).

By pressing <kbd>ctrl</kbd> + <kbd>b</kbd>, <kbd>ctrl</kbd> + <kbd>s</kbd> (save) I can save the `tmux` current state and then whenever I want it back I press <kbd>ctrl</kbd> + <kbd>b</kbd>, <kbd>ctrl</kbd> + <kbd>r</kbd> (restore).

Hope this helps. :blush:

**Comment by Goddard** [comment]
While that is true, it would be pretty cool if it was just a feature of the program similar to how Chromium has the restore feature.

**Comment by IonicaBizau** [comment]
@Goddard Contributions are still welcome. I just don't have time to implement it, but if somebody opens a nice PR I'm glad to review and probably merge it. :smile:
